version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    # restart: always
    ports:
      - 27017:27017
    volumes:
      - expressjs-inversity:/database/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=expressjs-inversity-practise
    logging:
      driver: none
  server:
    depends_on:
      - mongodb
    build:
      context: ./
      target: dev
    restart: always
    container_name: server
    command: npm run start:dev
    volumes:
      - .:/src
    ports:
      - 3000:3000
    environment:
      - NOVE_END:development
volumes:
  expressjs-inversity:

    